name: GitHub Actions Demo
on: [ push ]
jobs: 
  Test:
    runs-on: ubuntu-lastest
    steps:
      -run: echo "🎉 The job was autimatically triggered by a ${{ github.event_name }} event."
      -run: pyjon main.py   