name: GitHub Actions Demo
on: [ push ]
jobs: 
  Test:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
      - run: echo "🎉 The job was autimatically triggered by a ${{ github.event_name }} event."
      - run: python main.py   